# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev23+g9b97ae9.d20220806'
__version_tuple__ = version_tuple = (0, 1, 'dev23', 'g9b97ae9.d20220806')
